# Generated by Django 4.2.9 on 2024-05-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('summary', models.TextField()),
            ],
        ),
    ]
