# Generated by Django 4.2.9 on 2024-06-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_apimovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimovies',
            name='image',
        ),
        migrations.AddField(
            model_name='apimovies',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apimovies',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apimovies',
            name='release_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apimovies',
            name='release_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='apimovies',
            name='release_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='apimovies',
            name='title_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apimovies',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
