# Generated by Django 4.2.9 on 2024-06-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_apimovies_image_apimovies_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimovies',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apimovies',
            name='title_image_url',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
