# Generated by Django 4.2.9 on 2024-06-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_apimovies_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimovies',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
