# Generated by Django 4.2.9 on 2024-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_apimovies_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('release_year', models.CharField(blank=True, max_length=4, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('title_image_url', models.ImageField(default=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='apiMovies',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
