# Generated by Django 4.2.9 on 2024-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movies_delete_apimovies_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
